name: fyp_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  art_sweetalert: ^0.0.5
  curved_navigation_bar: ^1.0.6 #latest version
  cloud_firestore: ^5.6.1
  toggle_switch: ^2.3.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  permission_handler: ^11.3.1
  flutter_svg: ^1.0.0
  intl: ^0.20.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit: ^4.2.1

  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/


  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Regular.ttf
